@Project2_Debug_HostAddress = http://localhost:5282

POST {{Project2_Debug_HostAddress}}/member/register
Content-Type: application/json

{
  "account": "newbie",
  "name": "New Bie",
  "email": "new@example.com"
}

###
